# This file is a simple Gitlab-CI config file to run pytest

image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache py2-pip && pip install docker-compose

test:
  script:
  - export DJANGO_SETTINGS_MODULE=config.settings.test
  - export CELERY_BROKER_URL=redis://
  - export DATABASE_URL=postgres://postgres:@postgres:5432/achareh
  - docker-compose -f local.yml run django pytest
