# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# set the default branch
# default: empty, the default branch on GitHub
branch: master

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every day"

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix: pyup/

# Specify requirement files by hand, pyup seems to struggle to
# find the ones in the project_slug folder
requirements:
  - "requirements.txt"
  - "{{cookiecutter.project_slug}}/requirements/base.txt"
  - "{{cookiecutter.project_slug}}/requirements/local.txt"
  - "{{cookiecutter.project_slug}}/requirements/production.txt"
