# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# set the default branch
# default: empty, the default branch on GitHub
branch: master

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every day"

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix: pyup/
